default_stages: [commit]
exclude: node_modules/.*

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: mixed-line-ending

          - id: check-merge-conflict

          - id: check-case-conflict

          - id: check-symlinks

          - id: destroyed-symlinks

          - id: check-executables-have-shebangs

          - id: check-shebang-scripts-are-executable

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.1 # Should match additional_dependencies and package-lock.json
      hooks:
          - id: prettier
            additional_dependencies:
                # W/A: https://github.com/prettier/pre-commit/issues/16#issuecomment-713501862
                - prettier@2.6.0 # Should match rev and package-lock.json
                - '@doist/prettier-config@3.0.5' # Should match package-lock.json
