name: Ensure pre-commit checks pass

on:
    push:

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v4

            - uses: pre-commit/action@v2.0.0
              with:
                  extra_args: --all-files
